// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package info.airsen.serialize.tool;

public final class ProtobufOperator {
  private ProtobufOperator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface dataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool bool1 = 1;
    /**
     * <code>optional bool bool1 = 1;</code>
     */
    boolean hasBool1();
    /**
     * <code>optional bool bool1 = 1;</code>
     */
    boolean getBool1();

    // optional bool bool2 = 2;
    /**
     * <code>optional bool bool2 = 2;</code>
     */
    boolean hasBool2();
    /**
     * <code>optional bool bool2 = 2;</code>
     */
    boolean getBool2();

    // optional int64 int1 = 3;
    /**
     * <code>optional int64 int1 = 3;</code>
     */
    boolean hasInt1();
    /**
     * <code>optional int64 int1 = 3;</code>
     */
    long getInt1();

    // optional int64 int2 = 4;
    /**
     * <code>optional int64 int2 = 4;</code>
     */
    boolean hasInt2();
    /**
     * <code>optional int64 int2 = 4;</code>
     */
    long getInt2();

    // optional float float1 = 5;
    /**
     * <code>optional float float1 = 5;</code>
     */
    boolean hasFloat1();
    /**
     * <code>optional float float1 = 5;</code>
     */
    float getFloat1();

    // optional float float2 = 6;
    /**
     * <code>optional float float2 = 6;</code>
     */
    boolean hasFloat2();
    /**
     * <code>optional float float2 = 6;</code>
     */
    float getFloat2();

    // optional string string1 = 7;
    /**
     * <code>optional string string1 = 7;</code>
     */
    boolean hasString1();
    /**
     * <code>optional string string1 = 7;</code>
     */
    java.lang.String getString1();
    /**
     * <code>optional string string1 = 7;</code>
     */
    com.google.protobuf.ByteString
        getString1Bytes();

    // optional string string2 = 8;
    /**
     * <code>optional string string2 = 8;</code>
     */
    boolean hasString2();
    /**
     * <code>optional string string2 = 8;</code>
     */
    java.lang.String getString2();
    /**
     * <code>optional string string2 = 8;</code>
     */
    com.google.protobuf.ByteString
        getString2Bytes();
  }
  /**
   * Protobuf type {@code data}
   */
  public static final class data extends
      com.google.protobuf.GeneratedMessage
      implements dataOrBuilder {
    // Use data.newBuilder() to construct.
    private data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final data defaultInstance;
    public static data getDefaultInstance() {
      return defaultInstance;
    }

    public data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.airsen.serialize.tool.ProtobufOperator.internal_static_data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.airsen.serialize.tool.ProtobufOperator.internal_static_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.airsen.serialize.tool.ProtobufOperator.data.class, info.airsen.serialize.tool.ProtobufOperator.data.Builder.class);
    }

    public static com.google.protobuf.Parser<data> PARSER =
        new com.google.protobuf.AbstractParser<data>() {
      public data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<data> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool bool1 = 1;
    public static final int BOOL1_FIELD_NUMBER = 1;
    private boolean bool1_;
    /**
     * <code>optional bool bool1 = 1;</code>
     */
    public boolean hasBool1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool bool1 = 1;</code>
     */
    public boolean getBool1() {
      return bool1_;
    }

    // optional bool bool2 = 2;
    public static final int BOOL2_FIELD_NUMBER = 2;
    private boolean bool2_;
    /**
     * <code>optional bool bool2 = 2;</code>
     */
    public boolean hasBool2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool bool2 = 2;</code>
     */
    public boolean getBool2() {
      return bool2_;
    }

    // optional int64 int1 = 3;
    public static final int INT1_FIELD_NUMBER = 3;
    private long int1_;
    /**
     * <code>optional int64 int1 = 3;</code>
     */
    public boolean hasInt1() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 int1 = 3;</code>
     */
    public long getInt1() {
      return int1_;
    }

    // optional int64 int2 = 4;
    public static final int INT2_FIELD_NUMBER = 4;
    private long int2_;
    /**
     * <code>optional int64 int2 = 4;</code>
     */
    public boolean hasInt2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 int2 = 4;</code>
     */
    public long getInt2() {
      return int2_;
    }

    // optional float float1 = 5;
    public static final int FLOAT1_FIELD_NUMBER = 5;
    private float float1_;
    /**
     * <code>optional float float1 = 5;</code>
     */
    public boolean hasFloat1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float float1 = 5;</code>
     */
    public float getFloat1() {
      return float1_;
    }

    // optional float float2 = 6;
    public static final int FLOAT2_FIELD_NUMBER = 6;
    private float float2_;
    /**
     * <code>optional float float2 = 6;</code>
     */
    public boolean hasFloat2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float float2 = 6;</code>
     */
    public float getFloat2() {
      return float2_;
    }

    // optional string string1 = 7;
    public static final int STRING1_FIELD_NUMBER = 7;
    private java.lang.Object string1_;
    /**
     * <code>optional string string1 = 7;</code>
     */
    public boolean hasString1() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string string1 = 7;</code>
     */
    public java.lang.String getString1() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          string1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string1 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getString1Bytes() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string string2 = 8;
    public static final int STRING2_FIELD_NUMBER = 8;
    private java.lang.Object string2_;
    /**
     * <code>optional string string2 = 8;</code>
     */
    public boolean hasString2() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string string2 = 8;</code>
     */
    public java.lang.String getString2() {
      java.lang.Object ref = string2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          string2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string2 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getString2Bytes() {
      java.lang.Object ref = string2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bool1_ = false;
      bool2_ = false;
      int1_ = 0L;
      int2_ = 0L;
      float1_ = 0F;
      float2_ = 0F;
      string1_ = "";
      string2_ = "";
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.airsen.serialize.tool.ProtobufOperator.data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(info.airsen.serialize.tool.ProtobufOperator.data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements info.airsen.serialize.tool.ProtobufOperator.dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.airsen.serialize.tool.ProtobufOperator.internal_static_data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.airsen.serialize.tool.ProtobufOperator.internal_static_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.airsen.serialize.tool.ProtobufOperator.data.class, info.airsen.serialize.tool.ProtobufOperator.data.Builder.class);
      }

      // Construct using info.airsen.serialize.tool.ProtobufOperator.data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bool1_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        bool2_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        int1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        int2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        float1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        float2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        string1_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        string2_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.airsen.serialize.tool.ProtobufOperator.internal_static_data_descriptor;
      }

      public info.airsen.serialize.tool.ProtobufOperator.data getDefaultInstanceForType() {
        return info.airsen.serialize.tool.ProtobufOperator.data.getDefaultInstance();
      }

      public info.airsen.serialize.tool.ProtobufOperator.data build() {
        info.airsen.serialize.tool.ProtobufOperator.data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public info.airsen.serialize.tool.ProtobufOperator.data buildPartial() {
        info.airsen.serialize.tool.ProtobufOperator.data result = new info.airsen.serialize.tool.ProtobufOperator.data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bool1_ = bool1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bool2_ = bool2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int1_ = int1_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.int2_ = int2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.float1_ = float1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.float2_ = float2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.string1_ = string1_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.string2_ = string2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      // optional bool bool1 = 1;
      private boolean bool1_ ;
      /**
       * <code>optional bool bool1 = 1;</code>
       */
      public boolean hasBool1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool bool1 = 1;</code>
       */
      public boolean getBool1() {
        return bool1_;
      }
      /**
       * <code>optional bool bool1 = 1;</code>
       */
      public Builder setBool1(boolean value) {
        bitField0_ |= 0x00000001;
        bool1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool1 = 1;</code>
       */
      public Builder clearBool1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bool1_ = false;
        onChanged();
        return this;
      }

      // optional bool bool2 = 2;
      private boolean bool2_ ;
      /**
       * <code>optional bool bool2 = 2;</code>
       */
      public boolean hasBool2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool bool2 = 2;</code>
       */
      public boolean getBool2() {
        return bool2_;
      }
      /**
       * <code>optional bool bool2 = 2;</code>
       */
      public Builder setBool2(boolean value) {
        bitField0_ |= 0x00000002;
        bool2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool2 = 2;</code>
       */
      public Builder clearBool2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bool2_ = false;
        onChanged();
        return this;
      }

      // optional int64 int1 = 3;
      private long int1_ ;
      /**
       * <code>optional int64 int1 = 3;</code>
       */
      public boolean hasInt1() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 int1 = 3;</code>
       */
      public long getInt1() {
        return int1_;
      }
      /**
       * <code>optional int64 int1 = 3;</code>
       */
      public Builder setInt1(long value) {
        bitField0_ |= 0x00000004;
        int1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int1 = 3;</code>
       */
      public Builder clearInt1() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int1_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 int2 = 4;
      private long int2_ ;
      /**
       * <code>optional int64 int2 = 4;</code>
       */
      public boolean hasInt2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 int2 = 4;</code>
       */
      public long getInt2() {
        return int2_;
      }
      /**
       * <code>optional int64 int2 = 4;</code>
       */
      public Builder setInt2(long value) {
        bitField0_ |= 0x00000008;
        int2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int2 = 4;</code>
       */
      public Builder clearInt2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        int2_ = 0L;
        onChanged();
        return this;
      }

      // optional float float1 = 5;
      private float float1_ ;
      /**
       * <code>optional float float1 = 5;</code>
       */
      public boolean hasFloat1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float float1 = 5;</code>
       */
      public float getFloat1() {
        return float1_;
      }
      /**
       * <code>optional float float1 = 5;</code>
       */
      public Builder setFloat1(float value) {
        bitField0_ |= 0x00000010;
        float1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float float1 = 5;</code>
       */
      public Builder clearFloat1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        float1_ = 0F;
        onChanged();
        return this;
      }

      // optional float float2 = 6;
      private float float2_ ;
      /**
       * <code>optional float float2 = 6;</code>
       */
      public boolean hasFloat2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float float2 = 6;</code>
       */
      public float getFloat2() {
        return float2_;
      }
      /**
       * <code>optional float float2 = 6;</code>
       */
      public Builder setFloat2(float value) {
        bitField0_ |= 0x00000020;
        float2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float float2 = 6;</code>
       */
      public Builder clearFloat2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        float2_ = 0F;
        onChanged();
        return this;
      }

      // optional string string1 = 7;
      private java.lang.Object string1_ = "";
      /**
       * <code>optional string string1 = 7;</code>
       */
      public boolean hasString1() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string string1 = 7;</code>
       */
      public java.lang.String getString1() {
        java.lang.Object ref = string1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          string1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string1 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getString1Bytes() {
        java.lang.Object ref = string1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string1 = 7;</code>
       */
      public Builder setString1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        string1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string1 = 7;</code>
       */
      public Builder clearString1() {
        bitField0_ = (bitField0_ & ~0x00000040);
        string1_ = getDefaultInstance().getString1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string1 = 7;</code>
       */
      public Builder setString1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        string1_ = value;
        onChanged();
        return this;
      }

      // optional string string2 = 8;
      private java.lang.Object string2_ = "";
      /**
       * <code>optional string string2 = 8;</code>
       */
      public boolean hasString2() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string string2 = 8;</code>
       */
      public java.lang.String getString2() {
        java.lang.Object ref = string2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          string2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string2 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getString2Bytes() {
        java.lang.Object ref = string2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string2 = 8;</code>
       */
      public Builder setString2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        string2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string2 = 8;</code>
       */
      public Builder clearString2() {
        bitField0_ = (bitField0_ & ~0x00000080);
        string2_ = getDefaultInstance().getString2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string2 = 8;</code>
       */
      public Builder setString2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        string2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:data)
    }

    static {
      defaultInstance = new data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\"\202\001\n\004data\022\r\n\005bool1\030\001 \001(\010\022\r\n\005" +
      "bool2\030\002 \001(\010\022\014\n\004int1\030\003 \001(\003\022\014\n\004int2\030\004 \001(\003\022" +
      "\016\n\006float1\030\005 \001(\002\022\016\n\006float2\030\006 \001(\002\022\017\n\007strin" +
      "g1\030\007 \001(\t\022\017\n\007string2\030\010 \001(\tB0\n\032info.airsen" +
      ".serialize.toolB\020ProtobufOperatorH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_descriptor,
              new java.lang.String[] { "Bool1", "Bool2", "Int1", "Int2", "Float1", "Float2", "String1", "String2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
